server:
  port: 8191
  servlet:
    context-path: /market-stat
utils:
  cart:
    prefix: SPRING_WEB_
integrations:
  core-service:
    url: http://localhost:8189/market-core
    connect-timeout: 5000
    read-timeout: 10000
    write-timeout: 5000